### PR TITLE
Adding typescript types.

### PR DESCRIPTION
**Pull request by vangorra**
This makes the modules easy to use with typescipt.

### CODE REVIEW

**Comment by jriecken** [comment]
Thanks!

**Comment by jriecken** [comment]
I published version `0.5.1` if you need to pull one with the TS definition in it

**Comment by vangorra** [comment]
Thanks!

**Comment by tbranyen** [comment]
While using these types, I hit the following error:

```
lib/index.ts:36:27: error TS2554: Expected 0 arguments, but got 1.
```

Looks like the constructor was never defined. I'll update and submit a PR.

**Pull request merged**
